# Generated by Django 2.2.3 on 2019-08-04 18:39
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190801_0837'),
    ]

    operations = [
        HStoreExtension()
    ]
