swagger: '2.0'

info :
  version: 1.0.0
  title: Board API
  description: An API to manage boards for the backend of ilconto app
  
schemes: 
  - http
  - https
  
host: localhost
basePath: /v1

paths:
  /boards:
    get:
      summary: Gets some boards
      description: Returns a list containing all boards, with only their basic information 
      responses:
        200:
          description: A list of Boards
          schema:
            type: array
            items: 
              required:
                - id
              properties:
                boardId:
                  type: integer
                boardName:
                  type: string

    post:
      summary: Creates a board
      description: Initializing a new board.
      parameters:
        - name: boardName
          in: body
          description: The name of the new board.
          type: string
        - name: members
          in: body
          description: The list of emails of members to initialize the boards.
          schema:
            type: array
            items:
              required:
                - email
              properties:
                email:
                  type: string
      responses:
        204:
          description: Board was succesfully created.
        400:
          description: Board could not be created.
  
  /boards/{boardId} :
    get:
      summary: Gets a unique board by its id
      description: "Gets all information of the board, including members and respective scores."
      parameters:
        - name: boardId
          in: path
          required: true
          description: The board's unique id
          type: integer
      responses:
        200:
          description: A board
          schema:
            required:
              - boardId
              - boardName
              - boardMembers
            properties:
              boardId:
                type: integer
              boardName:
                type: string
              boardMembers: 
                type: string
              
        404:
          description: The Board does not exists.