swagger: '2.0'

info :
  version: 1.0.0
  title: Board API
  description: An API to manage boards for the backend of ilconto app
  
schemes: 
  - http
  - https
  
host: localhost
basePath: /v1

paths:
  /boards:


    post:
      summary: Creates a board
      description: Initializing a new board.
      parameters:
        - name: boardInfo
          in: body
          description: The name of the new board.
          schema:
            $ref: '#/definitions/BoardInitInfo'
        
      responses:
        204:
          description: Board was succesfully created.
        400:
          description: Board could not be created.
  
  /boards/{boardId} :
    get:
      summary: Gets a unique board by its id
      description: "Gets all information of the board, including members and respective scores."
      parameters:
        - name: boardId
          in: path
          required: true
          description: The board's unique id
          type: integer

      responses:
        200:
          description: A board
          schema:
            required:
              - boardId
              - boardName
              - boardMembers
            properties:
              boardId:
                type: integer
                example: 3456
              boardName:
                type: string
                example: "This is my board"
              boardMembers: 
                  type: array
                  items:
                    type: string
                    example: "johnny"
                
              
        404:
          description: The Board does not exists.

  /boards/{boardId}/reset/{userID} :
    patch :
      summary: Reset a member's score
      description: "Gets all information of the board, including members and respective scores."
      parameters:
        - name: boardId
          in: path
          required: true
          description: The board's unique id
          type: integer
        - name: userID
          in: path
          required: true
          description: The user id of the member to reset
      responses:
        204:
          description: Confirms the reset
          
definitions:
  BoardInitInfo :
    description: Information needed to create a new board
    properties:
      boardName:
        type: string
        example: "Awesome board's name"
        description: board's name
      members:
        type: array
        items:
          required:
            - email
          properties:
            email:
              type: string
              example: "johndoe@example.com"
          description: board's member on init
    required:
      - boardName
      
      







  