# Generated by Django 2.2.4 on 2019-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_appuser_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='activation_hash',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
