# Generated by Django 2.2.3 on 2019-08-04 18:50

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190804_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='scores',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'test': 'test'}),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
